### ISSUE TITLE
Improving message traceability

### ISSUE THREAD

**Issue by abellina** [openucx/ucx#4725]
This is an issue that was discussed a bit in the hackathon. The question is, could UCP produce a small status "receipt" when a message is completed (at the callback likely), with basic information on what happened to the message.

I think that the minimum thing we'd want to see is what transport was used (e.g. cuda_ipc), was it pipelined? what rendezvous scheme was used?

I could see wanting to know what NIC was used for example for the IB transfer to be really useful, so depending on the transport there could be extra information that would be handy. That said, getting the basic info is probably a good starting point.

I am not sure what kind of effort this is, but thought to file so it can be discussed.

**Comment by petro-rudenko** [comment]
https://github.com/openucx/ucx/wiki/Statistics
You can get  something like this:
```
  ucp_worker-0x7ffff20c8b70:
    rx_eager_msg: 1
    rx_sync_msg: 0
    rx_eager_chunk_exp: 1
    rx_eager_chunk_unexp: 0
    rx_rndv_rts_exp: 0
    rx_rndv_rts_unexp: 0
```
